const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={done:new Set(JSON.parse(localStorage.getItem('game-within')||'[]')),sound:true,game:null};
const modal=$('#modal'),stage=$('#gameStage');
let audio;
function beep(freq=440,d=.08){if(!state.sound)return;audio??=new AudioContext();const o=audio.createOscillator(),g=audio.createGain();o.frequency.value=freq;o.type='square';g.gain.setValueAtTime(.04,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+d)}
function update(){state.done.forEach(g=>$(`[data-game="${g}"]`)?.classList.add('completed'));$('#fragments').textContent=`${state.done.size} / 6`;$('#meterFill').style.width=`${state.done.size/6*100}%`;updateDuelAccess();if(state.done.size===6){$('#vault').classList.add('unlocked');$('#lock').textContent='★';$('#vaultTitle').textContent='LEGENDARY CHEST OPENED!';$('#vaultText').textContent='You conquered every world and became a Blockverse champion.'}}
function win(game){if(!state.done.has(game)){state.done.add(game);localStorage.setItem('game-within',JSON.stringify([...state.done]));$('#toast').textContent='POWER CUBE EARNED!';$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2200)}beep(880,.2);update();stage.innerHTML=`<div class="game-ui"><p class="eyebrow">CHALLENGE COMPLETE</p><h2>YOU WON!</h2><p>You earned one shiny Power Cube.</p><button class="primary" onclick="closeGame()">BACK TO GAMES</button></div>`}
function openGame(game){state.game=game;modal.classList.add('open');modal.setAttribute('aria-hidden','false');$('#gameNumber').textContent='GAME 0'+({memory:1,react:2,dodge:3,coins:4,math:5,target:6}[game]);({memory:memoryGame,react:reactGame,dodge:dodgeGame,coins:coinGame,math:mathGame,target:targetGame}[game])()}
function closeGame(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true');stage.innerHTML='';state.game=null}
$$('.cabinet').forEach(c=>c.querySelector('button').onclick=()=>openGame(c.dataset.game));$('#closeBtn').onclick=closeGame;document.addEventListener('keydown',e=>{if(e.key==='Escape')closeGame()});
$('#enterBtn').onclick=()=>$('#arcade').scrollIntoView();$('#soundBtn').onclick=e=>{state.sound=!state.sound;e.currentTarget.textContent=`SOUND: ${state.sound?'ON':'OFF'}`;beep()};$('#resetBtn').onclick=()=>{state.done.clear();localStorage.removeItem('game-within');$$('.cabinet').forEach(c=>c.classList.remove('completed'));$('#vault').classList.remove('unlocked');$('#lock').textContent='×';$('#vaultTitle').textContent='TREASURE LOCKED';$('#vaultText').textContent='Win every game to open the legendary Blockverse chest.';update()};
function memoryGame(){let seq=[],input=[],level=1,busy=false;stage.innerHTML=`<div class="game-ui"><p class="eyebrow">// GHOST SIGNAL</p><h2>REPEAT THE PATTERN</h2><p id="memoryMsg">Reach sequence level 5.</p><div class="pads">${[0,1,2,3].map(i=>`<button class="pad" data-pad="${i}"></button>`).join('')}</div><button class="primary" id="memoryStart">START SIGNAL</button></div>`;const pads=$$('.pad');async function flash(i){pads[i].classList.add('lit');beep(260+i*130);await new Promise(r=>setTimeout(r,380));pads[i].classList.remove('lit');await new Promise(r=>setTimeout(r,100))}async function round(){busy=true;input=[];seq.push(Math.floor(Math.random()*4));$('#memoryMsg').textContent=`LEVEL ${level} — WATCH`;await new Promise(r=>setTimeout(r,450));for(const i of seq)await flash(i);busy=false;$('#memoryMsg').textContent=`LEVEL ${level} — YOUR TURN`}pads.forEach((p,i)=>p.onclick=async()=>{if(busy||!seq.length)return;await flash(i);input.push(i);const n=input.length-1;if(input[n]!==seq[n]){seq=[];level=1;$('#memoryMsg').textContent='SIGNAL LOST — TRY AGAIN';beep(90,.25);return}if(input.length===seq.length){level++;if(level>5)return win('memory');busy=true;setTimeout(round,600)}});$('#memoryStart').onclick=()=>{if(!busy){seq=[];level=1;round()}}}
function reactGame(){stage.innerHTML=`<div class="game-ui"><p class="eyebrow">// VOID TRIGGER</p><h2>WAIT FOR THE ANOMALY</h2><p id="reactMsg">Three clean hits to win.</p><div class="react-zone" id="reactZone">CLICK TO ARM</div></div>`;let armed=false,go=false,hits=0,timer,start;const zone=$('#reactZone');function arm(){if(armed)return;armed=true;go=false;zone.classList.remove('go');zone.textContent='WAIT...';timer=setTimeout(()=>{go=true;start=performance.now();zone.classList.add('go');zone.textContent='HIT NOW';beep(700)},1200+Math.random()*2500)}zone.onclick=()=>{if(!armed){arm();return}if(!go){clearTimeout(timer);armed=false;zone.textContent='TOO EARLY — CLICK TO REARM';beep(80,.2);return}const ms=Math.round(performance.now()-start);hits++;armed=false;go=false;zone.classList.remove('go');$('#reactMsg').textContent=`HIT ${hits}/3 — ${ms}ms`;if(hits===3)return win('react');zone.textContent='CLICK TO ARM';beep(450+hits*100)}}
function dodgeGame(){stage.innerHTML=`<div class="game-ui"><p class="eyebrow">// LAST DRIFTER</p><h2>SURVIVE 12 SECONDS</h2><p id="dodgeMsg">Use ← → or drag your pointer.</p><div class="dodge-board" id="board"><div class="player" id="player"></div></div><button class="primary" id="dodgeStart">LAUNCH</button></div>`;const board=$('#board'),player=$('#player');let x=196,running=false,rocks=[],start,lastSpawn=0,raf;function pos(){player.style.left=x+'px'}pos();function move(clientX){const r=board.getBoundingClientRect();x=Math.max(0,Math.min(r.width-28,clientX-r.left-14));pos()}board.onpointermove=e=>{if(running)move(e.clientX)};function key(e){if(!running)return;if(e.key==='ArrowLeft')x=Math.max(0,x-24);if(e.key==='ArrowRight')x=Math.min(board.clientWidth-28,x+24);pos()}document.addEventListener('keydown',key,{signal:new AbortController().signal});function loop(t){if(!running)return;const elapsed=(t-start)/1000;$('#dodgeMsg').textContent=`${Math.max(0,12-elapsed).toFixed(1)} SECONDS`;if(elapsed>=12){running=false;return win('dodge')}if(t-lastSpawn>420){const el=document.createElement('i');el.className='rock';const rx=Math.random()*(board.clientWidth-24);el.style.left=rx+'px';el.style.top='-30px';board.append(el);rocks.push({el,x:rx,y:-30});lastSpawn=t}for(const r of rocks){r.y+=4.5;r.el.style.top=r.y+'px';if(r.y>board.clientHeight)r.el.remove();if(r.y+24>board.clientHeight-46&&r.y<board.clientHeight-16&&r.x+24>x&&r.x<x+28){running=false;rocks.forEach(o=>o.el.remove());$('#dodgeMsg').textContent='IMPACT — LAUNCH AGAIN';$('#dodgeStart').disabled=false;beep(70,.3);return}}rocks=rocks.filter(r=>r.y<board.clientHeight);raf=requestAnimationFrame(loop)}$('#dodgeStart').onclick=e=>{rocks.forEach(r=>r.el.remove());rocks=[];running=true;e.currentTarget.disabled=true;start=performance.now();lastSpawn=start;raf=requestAnimationFrame(loop)}}
function coinGame(){stage.innerHTML=`<div class="game-ui"><p class="eyebrow">COIN RUSH</p><h2>GRAB 10 COINS</h2><p id="coinMsg">10 seconds left · 0 / 10</p><div class="coin-field" id="coinField"></div><button class="primary" id="coinStart">START</button></div>`;let score=0,time=10,tick;const field=$('#coinField'),msg=$('#coinMsg');function spawn(){field.innerHTML='';const c=document.createElement('button');c.className='coin';c.textContent='★';c.style.left=Math.random()*(field.clientWidth-50)+'px';c.style.top=Math.random()*(field.clientHeight-50)+'px';c.onclick=()=>{score++;beep(500+score*25);if(score>=10){clearInterval(tick);return win('coins')}msg.textContent=`${time} seconds left · ${score} / 10`;spawn()};field.append(c)}$('#coinStart').onclick=e=>{score=0;time=10;e.currentTarget.style.display='none';spawn();tick=setInterval(()=>{time--;msg.textContent=`${time} seconds left · ${score} / 10`;if(time<=0){clearInterval(tick);field.innerHTML='';msg.textContent='TIME UP — TRY AGAIN';e.currentTarget.style.display='inline-block'}},1000)}}
function mathGame(){let round=0,answer=0;stage.innerHTML=`<div class="game-ui"><p class="eyebrow">MATH MAYHEM</p><h2 id="sum">READY?</h2><p id="mathMsg">Solve five in a row.</p><div class="answers" id="answers"></div><button class="primary" id="mathStart">START</button></div>`;function next(){const a=2+Math.floor(Math.random()*18),b=2+Math.floor(Math.random()*18);answer=a+b;$('#sum').textContent=`${a} + ${b} = ?`;const choices=[answer,answer+1+Math.floor(Math.random()*3),Math.max(1,answer-1-Math.floor(Math.random()*3)),answer+4+Math.floor(Math.random()*4)].sort(()=>Math.random()-.5);$('#answers').innerHTML=choices.map(n=>`<button class="answer">${n}</button>`).join('');$$('.answer').forEach(btn=>btn.onclick=()=>{if(+btn.textContent!==answer){round=0;beep(80,.2);$('#mathMsg').textContent='OOPS! STREAK RESET';return next()}round++;beep(600);if(round===5)return win('math');$('#mathMsg').textContent=`${round} / 5 CORRECT`;next()})}$('#mathStart').onclick=e=>{e.currentTarget.remove();next()}}
function awardMoonGems(amount){avatarData.moonGems+=amount;paintAvatar();const reward=document.createElement('div');reward.className='moon-reward';reward.innerHTML=`<div><b>🌙 +${amount}</b><span>MOON GEMS EARNED!</span></div>`;document.body.append(reward);setTimeout(()=>reward.remove(),2400)}
function targetGame(){stage.innerHTML=`<div class="game-ui"><p class="eyebrow">TARGET SMASH</p><h2>HIT 8 TARGETS</h2><p id="targetMsg">Win to earn 3 Moon Gems.</p><div class="target-field" id="targetField"></div><button class="primary" id="targetStart">START</button></div>`;let hits=0;const field=$('#targetField'),msg=$('#targetMsg');function spawn(){field.innerHTML='';const t=document.createElement('button');t.className='moving-target';t.style.left=Math.random()*(field.clientWidth-62)+'px';t.style.top=Math.random()*(field.clientHeight-62)+'px';t.onclick=()=>{hits++;beep(420+hits*40);msg.textContent=`${hits} / 8 HITS`;if(hits===8){awardMoonGems(3);return win('target')}spawn()};field.append(t)}$('#targetStart').onclick=e=>{hits=0;e.currentTarget.remove();spawn()}}
function updateDuelAccess(){const btn=$('#duelBtn');if(!btn)return;const cubes=state.done.size;btn.disabled=cubes===0;btn.textContent=cubes?`ENTER DUEL · ${cubes} POWER CUBE${cubes===1?'':'S'}`:'EARN A POWER CUBE TO UNLOCK'}
$('#duelBtn').onclick=()=>{if(state.done.size)duelGame()};
function duelGame(){modal.classList.add('open');modal.setAttribute('aria-hidden','false');$('#gameNumber').textContent='POWER CUBE DUEL';const maxPlayer=3+state.done.size,maxBot=5;let player=maxPlayer,bot=maxBot,busy=false;stage.innerHTML=`<div class="battlefield"><p class="eyebrow">DUEL ARENA · ${state.done.size} POWER CUBES ACTIVE</p><div class="battle-hud"><div class="battle-player"><h3>YOU</h3><span id="playerHp">${player} / ${maxPlayer} HP</span><div class="health-track"><i id="playerHealth"></i></div></div><b>VS</b><div class="battle-bot"><h3>BLOCK BOT</h3><span id="botHp">${bot} / ${maxBot} HP</span><div class="health-track"><i id="botHealth"></i></div></div></div><div class="battle-log" id="battleLog"><b>◆</b><p>Choose your first move.</p></div><div class="battle-actions"><button data-move="attack">⚔️ ATTACK</button><button data-move="guard">🛡️ GUARD</button><button data-move="charge">⚡ CHARGE</button></div></div>`;const icons={attack:'⚔️',guard:'🛡️',charge:'⚡'},wins={attack:'charge',guard:'attack',charge:'guard'},buttons=$$('.battle-actions button');function bars(){$('#playerHp').textContent=`${player} / ${maxPlayer} HP`;$('#botHp').textContent=`${bot} / ${maxBot} HP`;$('#playerHealth').style.width=player/maxPlayer*100+'%';$('#botHealth').style.width=bot/maxBot*100+'%'}function finish(victory){buttons.forEach(b=>b.disabled=true);if(victory){awardMoonGems(2);$('#battleLog').innerHTML='<b>🏆</b><p>DUEL WON! +2 MOON GEMS</p>'}else $('#battleLog').innerHTML='<b>💥</b><p>THE BOT WON — TRY AGAIN</p>';setTimeout(()=>{$('#battleLog').innerHTML+=`<button class="primary" onclick="duelGame()">REMATCH</button>`},700)}buttons.forEach(btn=>btn.onclick=()=>{if(busy)return;busy=true;const move=btn.dataset.move,botMove=['attack','guard','charge'][Math.floor(Math.random()*3)];let message;if(move===botMove)message='Draw — no damage!';else if(wins[move]===botMove){bot--;message='Direct hit! Bot loses 1 HP.';beep(650)}else{player--;message='The bot hits! You lose 1 HP.';beep(120)}$('#battleLog').innerHTML=`<b>${icons[move]} ${icons[botMove]}</b><p>${message}</p>`;bars();if(bot<=0)return finish(true);if(player<=0)return finish(false);setTimeout(()=>{busy=false;$('#battleLog').innerHTML='<b>◆</b><p>Choose your next move.</p>'},650)})}
const createdGames=JSON.parse(localStorage.getItem('blockverse-games')||'[]');
function renderCreatedGames(){const grid=$('#communityGames');grid.innerHTML=createdGames.map((g,i)=>`<article class="cabinet community-card" style="--accent:${g.color}"><button class="delete-game" data-delete="${i}" title="Delete game">×</button><div class="cabinet-top"><span>PLAYER MADE</span></div><div class="game-art" style="--accent:${g.color}"><b>${g.type==='click'?'👆':g.type==='guess'?'❓':'💎'}</b></div><p class="genre">${g.type.toUpperCase()} · NEW</p><h3>${g.name.replace(/</g,'&lt;')}</h3><p>Created in Blockverse Studio.</p><button class="play-created" data-created="${i}">PLAY <span>▶</span></button></article>`).join('');$$('.play-created').forEach(b=>b.onclick=()=>playCreated(createdGames[+b.dataset.created]));$$('.delete-game').forEach(b=>b.onclick=()=>{createdGames.splice(+b.dataset.delete,1);saveCreated();renderCreatedGames()})}
function saveCreated(){localStorage.setItem('blockverse-games',JSON.stringify(createdGames))}
$('#createdColor').oninput=e=>$('#colorPreview').style.background=e.target.value;
$('#creatorForm').onsubmit=e=>{e.preventDefault();createdGames.push({name:$('#createdName').value.trim(),type:$('#createdType').value,color:$('#createdColor').value});saveCreated();renderCreatedGames();e.currentTarget.reset();$('#createdColor').value='#745cff';$('#creatorNote').textContent='Published! Your game is live in the community arcade.';beep(760,.15);$('#communityGames').scrollIntoView({behavior:'smooth'})};
function playCreated(g){modal.classList.add('open');modal.setAttribute('aria-hidden','false');$('#gameNumber').textContent='COMMUNITY GAME';if(g.type==='click')createdClick(g);if(g.type==='guess')createdGuess(g);if(g.type==='collect')createdCollect(g)}
function createdWin(name){beep(900,.2);stage.innerHTML=`<div class="game-ui"><p class="eyebrow">COMMUNITY WIN</p><h2>YOU BEAT ${name.replace(/</g,'&lt;')}!</h2><p>Player-made challenge complete.</p><button class="primary" onclick="closeGame()">BACK TO ARCADE</button></div>`}
function createdClick(g){let n=0,seconds=8,timer;stage.innerHTML=`<div class="game-ui" style="--game-color:${g.color}"><p class="eyebrow">${g.name}</p><h2>CLICK 20 TIMES</h2><p id="customMsg">8 seconds left</p><button class="big-click" id="bigClick">START</button></div>`;$('#bigClick').onclick=()=>{if(!timer)timer=setInterval(()=>{seconds--;$('#customMsg').textContent=`${seconds} seconds left · ${n}/20`;if(seconds<=0){clearInterval(timer);timer=null;n=0;seconds=8;$('#customMsg').textContent='TIME UP — TRY AGAIN'}},1000);n++;$('#bigClick').textContent=n;beep(300+n*12);if(n>=20){clearInterval(timer);createdWin(g.name)}}}
function createdGuess(g){const secret=1+Math.floor(Math.random()*20);stage.innerHTML=`<div class="game-ui" style="--game-color:${g.color}"><p class="eyebrow">${g.name}</p><h2>NUMBER QUEST</h2><p id="guessMsg">Guess a number from 1 to 20.</p><input class="guess-input" id="guessInput" type="number" min="1" max="20"><button class="primary" id="guessBtn">GUESS</button></div>`;$('#guessBtn').onclick=()=>{const n=+$('#guessInput').value;if(n===secret)return createdWin(g.name);$('#guessMsg').textContent=n<secret?'Too low — go higher!':'Too high — go lower!';beep(120,.1)}}
function createdCollect(g){let count=0,time=12,timer;stage.innerHTML=`<div class="game-ui" style="--game-color:${g.color}"><p class="eyebrow">${g.name}</p><h2>COLLECT 12 GEMS</h2><p id="gemMsg">12 seconds left · 0/12</p><div class="created-game-zone" id="gemField"></div><button class="primary" id="gemStart">START</button></div>`;const field=$('#gemField');function gem(){field.innerHTML='';const x=document.createElement('button');x.className='gem';x.style.left=Math.random()*(field.clientWidth-50)+'px';x.style.top=Math.random()*(field.clientHeight-50)+'px';x.onclick=()=>{count++;beep(500+count*20);if(count===12){clearInterval(timer);return createdWin(g.name)}$('#gemMsg').textContent=`${time} seconds left · ${count}/12`;gem()};field.append(x)}$('#gemStart').onclick=e=>{e.currentTarget.remove();gem();timer=setInterval(()=>{time--;$('#gemMsg').textContent=`${time} seconds left · ${count}/12`;if(time<=0){clearInterval(timer);field.innerHTML='';$('#gemMsg').textContent='TIME UP — CLOSE AND TRY AGAIN'}},1000)}}
const avatarData=JSON.parse(localStorage.getItem('blockverse-avatar')||'{"skin":"#ffd13c","shirt":"#297ee5","pants":"#2e3741","accessory":"none"}');
avatarData.moonGems??=0;avatarData.owned??=['classic'];avatarData.outfit??='classic';avatarData.face??='happy';if(avatarData.accessory!=='none'&&!avatarData.owned.includes(avatarData.accessory))avatarData.owned.push(avatarData.accessory);
const shopLooks={classic:{shirt:'#297ee5',pants:'#2e3741'},ninja:{shirt:'#20242a',pants:'#111318'},royal:{shirt:'#7956d8',pants:'#eee7ff'},forest:{shirt:'#2f9d50',pants:'#674429'}};
function shirtPattern(d){if(!d)return'';if(d.pattern==='solid')return d.main;if(d.pattern==='split')return`linear-gradient(90deg,${d.main} 50%,${d.second} 50%)`;if(d.pattern==='stripes')return`repeating-linear-gradient(135deg,${d.main} 0 14px,${d.second} 14px 28px)`;return`conic-gradient(${d.main} 25%,${d.second} 0 50%,${d.main} 0 75%,${d.second} 0) 0/24px 24px`}
function paintAvatar(){document.documentElement.style.setProperty('--skin',avatarData.skin);document.documentElement.style.setProperty('--shirt',avatarData.shirt);document.documentElement.style.setProperty('--pants',avatarData.pants);document.documentElement.style.setProperty('--shirt-design',avatarData.design?shirtPattern(avatarData.design):avatarData.shirt);$$('.player-avatar').forEach(a=>{a.classList.remove('accessory-cap','accessory-crown','face-happy','face-cool','face-silly','face-brave','face-surprised');if(avatarData.accessory!=='none')a.classList.add('accessory-'+avatarData.accessory);a.classList.add('face-'+avatarData.face)});$$('[data-face]').forEach(b=>b.classList.toggle('active',b.dataset.face===avatarData.face));$('#coinBalance').textContent=avatarData.moonGems;localStorage.setItem('blockverse-avatar',JSON.stringify(avatarData));renderShop()}
function isEquipped(item){return item==='cap'||item==='crown'?avatarData.accessory===item:avatarData.outfit===item}
function equipItem(item){if(item==='cap'||item==='crown')avatarData.accessory=item;else{avatarData.outfit=item;avatarData.design=null;Object.assign(avatarData,shopLooks[item])}$('#skinColor').value=avatarData.skin;$('#shirtColor').value=avatarData.shirt;$('#pantsColor').value=avatarData.pants;paintAvatar();$('#shopNote').textContent=`${item[0].toUpperCase()+item.slice(1)} equipped!`;beep(700)}
function renderShop(){$$('.shop-item').forEach(card=>{const item=card.dataset.item,owned=avatarData.owned.includes(item),equipped=isEquipped(item),btn=card.querySelector('button');card.classList.toggle('owned',owned);card.classList.toggle('equipped',equipped);card.querySelector('p').textContent=equipped?'EQUIPPED':owned?'OWNED':(item==='cap'||item==='crown'?'ACCESSORY':'CLOTHING');btn.textContent=equipped?'✓ EQUIPPED':owned?'EQUIP':`🌙 ${card.dataset.price}`})}
$$('.shop-item').forEach(card=>card.querySelector('button').onclick=()=>{const item=card.dataset.item,price=+card.dataset.price;if(!avatarData.owned.includes(item)){if(avatarData.moonGems<price){$('#shopNote').textContent='Not enough Moon Gems — win Target Smash to earn more!';$('#coinBalance').parentElement.classList.add('shop-flash');setTimeout(()=>$('#coinBalance').parentElement.classList.remove('shop-flash'),500);beep(80,.2);return}avatarData.moonGems-=price;avatarData.owned.push(item);$('#shopNote').textContent='Purchased with Moon Gems and equipped!'}equipItem(item)});
$$('.shop-tabs button').forEach((tab,i)=>tab.onclick=()=>{$$('.shop-tabs button').forEach(t=>t.classList.remove('active'));tab.classList.add('active');$$('.shop-item').forEach(card=>{const accessory=['cap','crown'].includes(card.dataset.item);card.style.display=i===0||(i===1&&accessory)||(i===2&&!accessory)?'block':'none'})});$$('[data-face]').forEach(b=>b.onclick=()=>{avatarData.face=b.dataset.face;paintAvatar();$('#shopNote').textContent=`${b.textContent.trim()} face equipped!`;beep(620)});
[['skinColor','skin'],['shirtColor','shirt'],['pantsColor','pants']].forEach(([id,key])=>{const el=$('#'+id);el.value=avatarData[key];el.oninput=()=>{avatarData[key]=el.value;if(key!=='skin'){avatarData.outfit='custom';avatarData.design=null}paintAvatar()}});$('#randomAvatar').onclick=()=>{const colors=['#ff4747','#23c768','#297ee5','#9b6cff','#ff8b35','#ffd429'];avatarData.skin=['#ffd13c','#a96e4b','#75452f','#f0b88a'][Math.floor(Math.random()*4)];avatarData.shirt=colors[Math.floor(Math.random()*colors.length)];avatarData.pants=colors[Math.floor(Math.random()*colors.length)];avatarData.outfit='custom';avatarData.design=null;avatarData.face=['happy','cool','silly','brave','surprised'][Math.floor(Math.random()*5)];const hats=['none',...avatarData.owned.filter(x=>x==='cap'||x==='crown')];avatarData.accessory=hats[Math.floor(Math.random()*hats.length)];$('#skinColor').value=avatarData.skin;$('#shirtColor').value=avatarData.shirt;$('#pantsColor').value=avatarData.pants;paintAvatar();beep(650)};
const clothingDesigns=JSON.parse(localStorage.getItem('blockverse-clothes')||'[]');
function saveClothes(){localStorage.setItem('blockverse-clothes',JSON.stringify(clothingDesigns))}
function renderClothes(){$('#myDesigns').innerHTML=clothingDesigns.map((d,i)=>`<article class="design-card ${avatarData.design?.id===d.id?'equipped':''}"><div class="design-swatch" style="background:${shirtPattern(d)}"></div><h4>${d.name.replace(/</g,'&lt;')}</h4><div class="design-actions"><button data-wear="${i}">${avatarData.design?.id===d.id?'WEARING':'EQUIP'}</button><button class="remove-design" data-remove="${i}">×</button></div></article>`).join('');$$('[data-wear]').forEach(b=>b.onclick=()=>{avatarData.design=clothingDesigns[+b.dataset.wear];avatarData.outfit='design';avatarData.shirt=avatarData.design.main;$('#shirtColor').value=avatarData.shirt;paintAvatar();renderClothes();$('#shopNote').textContent='Your custom design is equipped!';beep(720)});$$('[data-remove]').forEach(b=>b.onclick=()=>{const d=clothingDesigns[+b.dataset.remove];if(avatarData.design?.id===d.id){avatarData.design=null;avatarData.outfit='classic';Object.assign(avatarData,shopLooks.classic);paintAvatar()}clothingDesigns.splice(+b.dataset.remove,1);saveClothes();renderClothes()})}
$('#clothesForm').onsubmit=e=>{e.preventDefault();const d={id:Date.now(),name:$('#clothesName').value.trim(),main:$('#clothMain').value,second:$('#clothSecond').value,pattern:$('#clothPattern').value};clothingDesigns.push(d);saveClothes();avatarData.design=d;avatarData.outfit='design';avatarData.shirt=d.main;$('#shirtColor').value=d.main;paintAvatar();renderClothes();e.currentTarget.reset();$('#shopNote').textContent='New clothing created and equipped!';beep(850,.18)};
renderCreatedGames();paintAvatar();renderClothes();
update();
